title: zigdata.org
tagline: data w/zig
email: zigzacks@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  data w/zig
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
google_analytics:
plugins:
  - jekyll-feed
