title: zigdata.org
tagline: data w/zig
show_downloads: true

url: "https://ziggyzacks.github.io"

google_analytics: UA-109502885

# for when I'm dumb with the date
future: true

author :
  name : Ziggy Zacks
  email : zigzacks@gmail.com
  github : ziggyzacks
